apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJnaGNyLmlvIjogewogICAgICAgICAgICAgICAgICAgICAgICAiYXV0aCI6ICJRVzUwYjI1TmIzTnJkbWx1T21kcGRHaDFZbDl3WVhSZk1URkJUak5DTjBoSk1GUjNRekpQV2toM1JWSlZSVjlwZVVNMVJqaHRVWFJUUmtaQlJEbE5kamxIV2pNek1uRk1jMWw2VWxKV1NXODBSMnBSUTNCTWIyNDBNMUJFUnpNMlRFVmljVGRRYlZOWGN3PT0iCiAgICAgICAgICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgICAgIH0sCiAgImN1cnJlbnRDb250ZXh0IjogImRlc2t0b3AtbGludXgiLAogICJwbHVnaW5zIjogewogICAgIi14LWNsaS1oaW50cyI6IHsKICAgICAgImVuYWJsZWQiOiAidHJ1ZSIKICAgIH0sCiAgICAiZGVidWciOiB7CiAgICAgICJob29rcyI6ICJleGVjIgogICAgfSwKICAgICJzY291dCI6IHsKICAgICAgImhvb2tzIjogInB1bGwsYnVpbGR4IGJ1aWxkIgogICAgfQogIH0sCiAgImZlYXR1cmVzIjogewogICAgImhvb2tzIjogInRydWUiCiAgfQp9
type: kubernetes.io/dockerconfigjson
